apps/bills/urls.py
# -*- coding: utf-8 -*-

__author__ = 'netcharm'

#######################

from django.conf.urls import patterns, url

from dajaxice.core import dajaxice_autodiscover
dajaxice_autodiscover()

import views
import utils

#from models import bills

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('apps.bills.views',
    # Examples:
    # url(r'^$', 'apps.views.home', name='home'),
    # url(r'^apps/', include('apps.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),

    # Home List
    url(r'^$', views.index, name='index'),

    # Config Actions
    url(r'^config/$', views.configs.list, name='configs.list'),
    url(r'^config/add/$', views.configs.add, name='configs.add'),
    url(r'^config/(?P<config_id>(\w|\W)+)/edit/$', views.configs.edit, name='configs.edit'),
    url(r'^config/(?P<config_id>(\w|\W)+)/remove/$', views.configs.remove, name='configs.remove'),
    url(r'^config/get/$',views.configs.get, name='configs.get'),
    url(r'^config/set/$',views.configs.set, name='configs.set'),

    # bills Actions
    url(r'^search/$',views.bills.search, name='bills.search'),
    url(r'^list/$', views.bills.list, name='bills.list'),
    url(r'^add/$', views.bills.add, name='bills.add'),
    url(r'^(?P<bill_id>\d+)/edit/$', views.bills.edit, name='bills.edit'),
    url(r'^(?P<bill_id>\d+)/remove/$', views.bills.remove, name='bills.remove'),
    url(r'^(?P<bill_id>\d+)/$', views.bills.detail, name='bills.detail'),
    url(r'^export/$', views.bills._export, name='bills.export'),
    url(r'^import/$', views.bills._import, name='bills.import'),

    # Fixed Assets Actions
    url(r'^location/$', views.locations.list, name='bill.locations.list'),
    url(r'^location/add/$', views.locations.add, name='bill.locations.add'),
    url(r'^location/(?P<location_id>(\w|\W)+)/edit/$', views.locations.edit, name='bill.locations.edit'),
    url(r'^location/(?P<location_id>(\w|\W)+)/remove/$', views.locations.remove, name='bill.locations.remove'),

    # Statistic Actions
    url(r'^report/$', views.reports.list, name='bill.reports.list'),
    url(r'^report/(?P<report_id>(\w|\W)+)/data/$', views.reports.data_json, name='bill.reports.data'),

    # API url actions
    url(r'^api/add/bill/$', views.api.add_json, name='views.api.add.bill'),
    url(r'^api/test/$', views.api.test_json, name='views.api.test'),


)

apps/urls.py
# -*- coding: utf-8 -*-

__author__ = 'netcharm'

from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
#from django.contrib import admin
#admin.autodiscover()

from django.conf import settings

from dajaxice.core import dajaxice_autodiscover, dajaxice_config
dajaxice_autodiscover()

import apps
import views

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'apps.views.home', name='home'),
    # url(r'^apps/', include('apps.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    #url(r'^admin/', include(admin.site.urls)),
    
    # customize url
    url(r'^$', views.home, name='apps.home'),

    # Config Actions
    url(r'^config/$', views.configs.list, name='configs.list'),
    url(r'^config/add/$', views.configs.add, name='configs.add'),
    url(r'^config/(?P<config_id>(\w|\W)+)/edit/$', views.configs.edit, name='configs.edit'),
    url(r'^config/(?P<config_id>(\w|\W)+)/remove/$', views.configs.remove, name='configs.remove'),
    url(r'^config/get/$',views.configs.get, name='configs.get'),
    url(r'^config/set/$',views.configs.set, name='configs.set'),

    # API url actions
    url(r'^api/app/add/$', views.api.add_json, name='api.add.app'),
    url(r'^api/app/(?P<app_id>\d+)/get/$', views.api.get_json, name='api.app.get'),
    url(r'^api/app/(?P<app_id>\d+)/edit/$', views.api.edit_json, name='api.app.edit'),
    url(r'^api/app/(?P<app_id>\d+)/remove/$', views.api.remove_json, name='api.app.remove'),

    # app op function
    url(r'^(?P<app_id>\d+)/remove/$', views.apps.remove, name='apps.remove'),


    # My Apps
    url(r'^books/', include('apps.books.urls')),
    url(r'^bike/', include('apps.bike.urls')),
    url(r'^bills/', include('apps.bills.urls')),

    url(dajaxice_config.dajaxice_url, include('dajaxice.urls')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    
)

if settings.DEBUG:
    urlpatterns += patterns('django.contrib.staticfiles.views',
        url(r'^static/(?P<path>.*)$', 'serve'),
    )

apps/bills/models.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

# -*- coding: utf-8 -*-

__author__ = 'netcharm'

#from django.contrib import admin
from django.db import models

#from django.core.exceptions import ValidationError

from django.utils.translation import ugettext as _

from datetime import date

class Config(models.Model):
    key = models.CharField(_('Key'), max_length=32)
    value = models.CharField(_('Value'), max_length=256)

    def __unicode__(self):
        return self.key

    class Admin:
        pass


class FixedAsset(models.Model):
    today_str = format(u"(%s %s)" % (_("etc."), date.today().isoformat()))

    description            = models.CharField(_('Description'), max_length=256)
    realestate_certificate = models.CharField(_('Real Estate Number'), max_length=64, blank=True,  null=True)
    landuse_certificate    = models.CharField(_('Land Use Number'), max_length=64, blank=True,  null=True)

    owner                  = models.CharField(_('Owner'), max_length=128, blank=True,  null=True)
    id_number              = models.CharField(_('ID Number'), max_length=64, blank=True,  null=True)
    bought_date            = models.DateField(_('Bought Date'), blank=True, null=True, help_text=today_str)
    bought_price           = models.DecimalField(_('Bought Price'), default=0, max_digits=12, decimal_places=2, blank=True,  null=True)
    value                  = models.DecimalField(_('Value'), default=0, max_digits=12, decimal_places=2, blank=True,  null=True)
    country                = models.CharField(_('Country'), max_length=128, blank=True,  null=True)
    province               = models.CharField(_('Province'), max_length=128, blank=True,  null=True)
    city                   = models.CharField(_('City'), max_length=128, blank=True,  null=True)
    address                = models.TextField(_('Address'), max_length=256, blank=True,  null=True)
    latitude               = models.DecimalField(_('Latitude'), default=0, max_digits=8, decimal_places=5, blank=True,  null=True)
    longitude              = models.DecimalField(_('Longitude'), default=0, max_digits=8, decimal_places=5, blank=True,  null=True)
    altitude               = models.DecimalField(_('Altitude'), default=0, max_digits=8, decimal_places=5, blank=True,  null=True)
    acreage                = models.DecimalField(_('Acreage'), default=0, max_digits=8, decimal_places=2, blank=True,  null=True)
    tele                   = models.CharField(_('Telephone'), max_length=32, blank=True,  null=True)
    email                  = models.EmailField(_('E-Mail'), max_length=128, blank=True,  null=True)
    postal                 = models.CharField(_('Postal'), max_length=32, blank=True,  null=True)
    note                   = models.TextField(_('Note'), max_length=32, blank=True,  null=True)

    property_bank          = models.CharField(_('Property Bank'), max_length=128, blank=True,  null=True)
    property_user          = models.CharField(_('Property Name'), max_length=128, blank=True,  null=True)
    property_account       = models.CharField(_('Property Account'), max_length=64, blank=True,  null=True)
    property_tele          = models.CharField(_('Property Telephone'), max_length=32, blank=True,  null=True)
    property_email         = models.CharField(_('Property EMail'), max_length=32, blank=True,  null=True)
    property_contact       = models.CharField(_('Property Contact'), max_length=32, blank=True,  null=True)

    property_unitprice     = models.DecimalField(_('Property Unit Price'), default=1, max_digits=8, decimal_places=2, blank=True,  null=True)

    fulladdress            = ''
    property_cost          = 0

    def calc(self):
        self.fulladdress = '%s%s%s%s' % (self.country, self.province, self.city, self.address)
        if self.property_unitprice and self.acreage:
            self.property_cost = self.property_unitprice * self.acreage

        pass

    def __unicode__(self):
        self.calc()
        return self.description

    class Admin:
        pass


class Bill(models.Model):
    today_str = format(u"(%s %s)" % (_("etc."), date.today().isoformat()))
    date_format = [
        '%Y-%m',
        '%Y/%m',
        '%y/%m',
        '%m/%Y',
        '%m/%y',
    ]

    #serialnumber = models.CharField(_('Serial Number'), max_length=32)
    location = models.ForeignKey(FixedAsset, default=0, blank=True, null=True, verbose_name=_('Asset Location'))

    bill_date = models.DateField(_('Bill Date'), blank=True, null=True, help_text=today_str)

    private_electricity_last    = models.DecimalField(_('Last Month Electricity Count'), default=0, max_digits=8, decimal_places=2, blank=True,  null=True)
    private_electricity_current = models.DecimalField(_('Current Month Electricity Count'), default=0, max_digits=8, decimal_places=2, blank=True,  null=True)
    private_electricity_bill    = models.DecimalField(_('Current Month Electricity Fee'), default=0, max_digits=8, decimal_places=2)

    private_water_last    = models.DecimalField(_('Last Month Water Count'), default=0, max_digits=8, decimal_places=2, blank=True,  null=True)
    private_water_current = models.DecimalField(_('Current Month Water Count'), default=0, max_digits=8, decimal_places=2, blank=True,  null=True)
    private_water_bill    = models.DecimalField(_('Current Month Water Fee'), default=0, max_digits=8, decimal_places=2)

    public_electricity          = models.DecimalField(_('Public Electricity Fee'), default=0, max_digits=8, decimal_places=2, blank=True,  null=True)
    public_water                = models.DecimalField(_('Public Water Fee'), default=0, max_digits=8, decimal_places=2, blank=True,  null=True)
    public_electricity_elevator = models.DecimalField(_('Public Electricity Elevator Fee'), default=0, max_digits=8, decimal_places=2, blank=True,  null=True)
    public_water_relay          = models.DecimalField(_('Public Water Relay Fee'), default=0, max_digits=8, decimal_places=2, blank=True,  null=True)

    property_cost            = models.DecimalField(_('Property Fee'), default=0, max_digits=8, decimal_places=2)
    property_balance_last    = models.DecimalField(_('Last Property Balance'), default=0, max_digits=8, decimal_places=2, blank=True,  null=True)
    property_balance_current = models.DecimalField(_('Current Property Balance'), default=0, max_digits=8, decimal_places=2, blank=True,  null=True)


    #
    # Calculating the fee
    #
    water_unitprice = 0
    water_count = 0

    electricity_unitprice = 0
    electricity_count = 0

    property_unitprice = 0
    real_property_unitprice = 0

    total_fee_ew = 0
    total_fee_public = 0
    total_fee_all = 0

    def calc(self):
        if self.private_water_current and self.private_water_last:
            self.water_count = self.private_water_current - self.private_water_last
            if (self.private_water_bill >= 0) and (self.water_count > 0):
                self.water_unitprice = self.private_water_bill / self.water_count

        if self.private_electricity_current and self.private_electricity_last:
            self.electricity_count = self.private_electricity_current - self.private_electricity_last
            if (self.private_electricity_bill >= 0) and (self.electricity_count > 0):
                self.electricity_unitprice = self.private_electricity_bill / self.electricity_count

        if  self.property_cost and self.location and self.location.acreage:
            if (self.property_cost >= 0) and (self.location.acreage > 0):
                self.real_property_unitprice = self.property_cost / self.location.acreage

        if self.location and self.location.property_unitprice:
            self.property_unitprice = self.location.property_unitprice


        if self.private_water_bill and (self.private_water_bill >= 0):
            private_water_bill = self.private_water_bill
        else:
            private_water_bill = 0


        if self.private_electricity_bill and (self.private_electricity_bill >= 0):
            private_electricity_bill = self.private_electricity_bill
        else:
            private_electricity_bill = 0

        self.total_fee_ew = private_water_bill + private_electricity_bill


        if self.public_electricity and (self.public_electricity >= 0):
            public_electricity = self.public_electricity
        else:
            public_electricity = 0

        if self.public_electricity_elevator and (self.public_electricity_elevator >= 0):
            public_electricity_elevator = self.public_electricity_elevator
        else:
            public_electricity_elevator = 0

        if self.public_water and (self.public_water >= 0):
            public_water = self.public_water
        else:
            public_water = 0

        if self.public_water_relay and (self.public_water_relay >= 0):
            public_water_relay = self.public_water_relay
        else:
            public_water_relay = 0

        self.total_fee_public = public_electricity + public_electricity_elevator + public_water + public_water_relay


        if self.total_fee_ew:
            total_fee_ew = self.total_fee_ew
        else:
            total_fee_ew = 0

        if self.total_fee_public:
            total_fee_public = self.total_fee_public
        else:
            total_fee_public = 9

        if self.property_cost:
            property_cost = self.property_cost
        else:
            property_cost = 9

        self.total_fee_all = total_fee_ew + total_fee_public + property_cost

        pass

    def __unicode__(self):
        self.calc()
        return self.location

    class Admin:
        pass

apps/bills/forms.py
# -*- coding: utf-8 -*-

__author__ = 'netcharm'

from django import forms
#from django.contrib.admin import widgets

from models import Config, Bill, FixedAsset

class ConfigEditForm(forms.ModelForm):
    required_css_class = 'ui-state-highlight'
    error_css_class = 'ui-state-error'

    class Meta:
        model = Config

    def __init__(self, *args, **kwargs):
        super(ConfigEditForm, self).__init__(*args, **kwargs)

        self.fields['value'].widget.attrs['size']  = 128

    pass



class FixedAssetEditForm(forms.ModelForm):
    required_css_class = 'ui-state-highlight'
    error_css_class = 'ui-state-error'

    class Meta:
        model = FixedAsset

    def __init__(self, *args, **kwargs):
        super(FixedAssetEditForm, self).__init__(*args, **kwargs)

        for field in  self.fields:
            if   field == 'description':
                self.fields[field].widget.attrs['size'] = 96
            elif field == 'property_bank':
                self.fields[field].widget.attrs['size'] = 96
            elif field == 'property_user':
                self.fields[field].widget.attrs['size'] = 96
            # elif field == 'property_account':
            else:
                self.fields[field].widget.attrs['size'] = 32
    pass


class BillEditForm(forms.ModelForm):
    required_css_class = 'ui-state-highlight'
    error_css_class = 'ui-state-error'

    class Meta:
        model = Bill

    def __init__(self, *args, **kwargs):
        super(BillEditForm, self).__init__(*args, **kwargs)

        for field in  self.fields:
            if not self.fields[field].required:
                #self.fields[field].hidden_widget = forms.HiddenInput()
                if field == 'location'                    : continue

                if field == 'bill_date'                   : continue

                if field == 'private_electricity_last'    : continue
                if field == 'private_electricity_current' : continue
                if field == 'private_electricity_bill'    : continue

                if field == 'private_water_last'          : continue
                if field == 'private_water_current'       : continue
                if field == 'private_water_bill'          : continue

                if field == 'public_electricity'          : continue
                if field == 'public_water'                : continue
                if field == 'public_electricity_elevator' : continue
                if field == 'public_water_relay'          : continue

                if field == 'property_cost'               : continue
                if field == 'property_balance_last'       : continue
                if field == 'property_balance_current'    : continue

                self.fields[field].widget = forms.HiddenInput()
                pass

        pass

    pass


apps/bills/templates/default/bill_detail.html
{% extends "default/bills_generic.html" %}
{% load i18n %}
{% load markup %}

{% if bill %}
{% block title %}{{ bill.title }}{% endblock %}
{% endif %}

{% block navigator %}
        <!--suppress ALL -->
        <li class="action"><a href="/bills/add">{{ _("Add Bill") }}</a></li>
    {% if bill %}
        <li class="action"><a href="/bills/{{ bill.pk }}/edit">{{ _("Edit Bill") }}</a></li>
        <li class="action"><a href="/bills/{{ bill.pk }}/remove" onclick="return remove_one($(this).attr('href'), '{{ bill.title }}', '{{ _("Remove") }}', '');">{{ _("Remove") }}{{ _("Bill") }}</a></li>
    {% endif %}
{% endblock %}

{% block content %}

<div class="list_title">{{ _("Bill Detail") }}</div>
<div>
    {% if bill %}
    <table id="bill_detail" class="list_items">
        <tbody>
        </tbody>
    </table>
    {% endif %}
</div>

{% endblock %}

apps/bills/templates/default/bill_edit.html
{% extends "default/bills_generic.html" %}

{% load i18n %}
{% load static %}

{% block title %}{{ _("Bill") }} -> {{ bill.title|default:_("Add") }}{% endblock %}

{% block dajax_script %}
    <script type="text/javascript" src="{% get_static_prefix %}js/dajax/jquery.dajax.core.js"></script>
    {% load dajaxice_templatetags %}
    {% dajaxice_js_import %}
    <script type="text/javascript">
        function adjust_ui()
        {
            fit_ui_datepicker('#id_bill_date');
        }
    </script>
{% endblock %}

{% block navigator %}
{% endblock %}

{#{% block side_left %}#}
{#{% endblock %}#}

{% block content %}
<form id="bill_edit_form" enctype="multipart/form-data" action="." method="POST" accept-charset="utf-8">
    {% csrf_token %}
    <fieldset class="form_fields ui-widget-content">
        {{ form.as_ul }}
        <li>
            <input class="form_submit" type="submit" value="{{ _("Save") }}" title="{{ _("Save Data to System") }}"/>
        </li>
    </fieldset>
</form>
<script type="text/javascript">
    adjust_ui();    
</script>
{% endblock %}

apps/bills/templates/default/bill_item_edit.html
{% load i18n %}
{% load static %}

<form id="bill_edit_form" enctype="multipart/form-data" action="{{ app_root }}/api/add/bill/" method="POST" accept-charset="utf-8">
    {% csrf_token %}
    <fieldset class="ui-widget-content">

        <div>
            <dl class="ui-widget-content table-row location">
                {{ form.location.errors }}
                <dt class="ui-widget-header table-title">{{ _('Asset Location') }}</dt>
                <dt class="ui-widget-content table-cell-value">{{ form_add.location|default:'' }}</dt>
                <dt class="ui-widget-header table-title">{{ _('Asset Acreage') }}</dt>
                <dt class="ui-widget-content table-cell-value fee" id="id_acreage"></dt>
            </dl>
        </div>
        <dl class="ui-widget-content table-row">
            <dt class="ui-widget-header table-title">{{ _('Bill Date') }}</dt>
            <dt class="ui-widget-content table-cell-value">{{ form_add.bill_date|addstyle:"text-align: center;" }}</dt>
            <dt class="ui-widget-header table-title">{{ _('Property Fee') }}</dt>
            <dd class="ui-widget-content table-cell-value fee">{{ form_add.property_cost|default:''|addstyle:"text-align: center;" }}</dd>
        </dl>
        <hr class="ui-widget-content"/>
        <dl class="ui-widget-content table-row">
            <dd>
                <dl class="ui-widget-content " >
                    <dt class="ui-widget-header table-cell-header">{{ _('Last Electricity Count') }}</dt>
                    <dd class="ui-widget-content table-cell-value">{{ form_add.private_electricity_last|default:''|addstyle:"text-align: center;" }}</dd>
                    <dt class="ui-widget-header table-cell-header">{{ _('Current Electricity Count') }}</dt>
                    <dd class="ui-widget-content table-cell-value">{{ form_add.private_electricity_current|default:''|addstyle:"text-align: center;" }}</dd>
                    <dt class="ui-widget-header table-cell-header">{{ _('Real Electricity Usage') }}</dt>
                    <dd class="ui-widget-content table-cell-value" id="id_electricity_count">{{ form_add.electricity_count|default:'' }}</dd>
                    <dt class="ui-widget-header table-cell-header">{{ _('Real Electricity Fee') }}</dt>
                    <dd class="ui-widget-content table-cell-value fee">{{ form_add.private_electricity_bill|default:''|addstyle:"text-align: center;" }}</dd>
                </dl>
            </dd>
            <dd>
                <dl>
                    <dt class="ui-widget-header table-cell-header">{{ _('Last Water Count') }}</dt>
                    <dd class="ui-widget-content table-cell-value">{{ form_add.private_water_last|default:''|addstyle:"text-align: center;" }}</dd>
                    <dt class="ui-widget-header table-cell-header">{{ _('Current Water Count') }}</dt>
                    <dd class="ui-widget-content table-cell-value">{{ form_add.private_water_current|default:''|addstyle:"text-align: center;" }}</dd>
                    <dt class="ui-widget-header table-cell-header">{{ _('Real Water Usage') }}</dt>
                    <dd class="ui-widget-content table-cell-value" id="id_water_count">{{ form_add.water_count|default:'' }}</dd>
                    <dt class="ui-widget-header table-cell-header">{{ _('Real Water Fee') }}</dt>
                    <dd class="ui-widget-content table-cell-value fee" >{{ form_add.private_water_bill|default:''|addstyle:"text-align: center;" }}</dd>
                </dl>
            </dd>
            <dd>
                <dl>
                    <dt class="ui-widget-header table-cell-header">{{ _('Public Electricity Elevator Fee') }}</dt>
                    <dd class="ui-widget-content table-cell-value fee">{{ form_add.public_electricity_elevator|default:''|addstyle:"text-align: center;" }}</dd>
                    <dt class="ui-widget-header table-cell-header">{{ _('Public Water Relay Fee') }}</dt>
                    <dd class="ui-widget-content table-cell-value fee">{{ form_add.public_water_relay|default:''|addstyle:"text-align: center;" }}</dd>
                    <dt class="ui-widget-header table-cell-header">{{ _('Public Electricity Fee') }}</dt>
                    <dd class="ui-widget-content table-cell-value fee">{{ form_add.public_electricity|default:''|addstyle:"text-align: center;" }}</dd>
                    <dt class="ui-widget-header table-cell-header">{{ _('Public Water Fee') }}</dt>
                    <dd class="ui-widget-content table-cell-value fee">{{ form_add.public_water|default:''|addstyle:"text-align: center;" }}</dd>
                </dl>
            </dd>
        </dl>

        <!--{{ form.as_ul }}-->
        <li>
            <!--<input class="form_submit" type="submit" value="{{ _('Save') }}" title="{{ _('Save Data to System') }}" id="id_postform"/>-->
            <input class="form_submit" type="button" value="{{ _('Save') }}" title="{{ _('Save Data to System') }}" id="id_postjson"/>
        </li>
    </fieldset>
</form>
<script type="text/javascript">
//    adjust_ui();
    var locs = {
    {% if location_list %}
    {% for loc in location_list %}
        'pk{{ loc.pk }}': [{{ loc.acreage }}, {{ loc.property_cost }}],
    {% endfor %}
    {% endif %}
    }

    $('#id_location').bind('change', function(){
        $('#id_acreage').text(eval('locs.pk'+this.value)[0]);
        $('#id_property_cost').val(eval('locs.pk'+this.value)[1].toFixed(2));
    });


    $('#id_private_electricity_last').bind('input', function(){
        var count = $('#id_private_electricity_current').val() - $('#id_private_electricity_last').val();
        $('#id_electricity_count').text(count);
    });

    $('#id_private_electricity_current').bind('input', function(){
        var count = $('#id_private_electricity_current').val() - $('#id_private_electricity_last').val();
        $('#id_electricity_count').text(count);
    });

    $('#id_private_water_last').bind('input', function(){
        var count = $('#id_private_water_current').val() - $('#id_private_water_last').val();
        $('#id_water_count').text(count);
        //alert(count);
    });

    $('#id_private_water_current').bind('input', function(){
        var count = $('#id_private_water_current').val() - $('#id_private_water_last').val();
        $('#id_water_count').text(count);
        //alert(count);
    });

    $('#id_postform').bind('click', function(){


    });

    $('#id_postjson').button();

    $('#id_postjson').bind('click', function(){
        var csrfmiddlewaretoken            = $('input[name="csrfmiddlewaretoken"]').val();
        var id_location                    = $('#id_location').val();
        var id_bill_date                   = $('#id_bill_date').val();
        var id_property_cost               = $('#id_property_cost').val();
        var id_private_electricity_last    = $('#id_private_electricity_last').val();
        var id_private_electricity_current = $('#id_private_electricity_current').val();
        var id_private_electricity_bill    = $('#id_private_electricity_bill').val();
        var id_private_water_last          = $('#id_private_water_last').val();
        var id_private_water_current       = $('#id_private_water_current').val();
        var id_private_water_bill          = $('#id_private_water_bill').val();
        var id_public_electricity          = $('#id_public_electricity').val();
        var id_public_water                = $('#id_public_water').val();
        var id_public_electricity_elevator = $('#id_public_electricity_elevator').val();
        var id_public_water_relay          = $('#id_public_water_relay').val();

        //var dataString = 'name='+ name + '&email=' + email + '&phone=' + phone;
        var dataString =    'csrfmiddlewaretoken='          + csrfmiddlewaretoken +
                            '&location='                    + id_location +
                            '&bill_date='                   + id_bill_date +
                            '&property_cost='               + id_property_cost +
                            '&private_electricity_last='    + id_private_electricity_last +
                            '&private_electricity_current=' + id_private_electricity_current +
                            '&private_electricity_bill='    + id_private_electricity_bill +
                            '&private_water_last='          + id_private_water_last +
                            '&private_water_current='       + id_private_water_current +
                            '&private_water_bill='          + id_private_water_bill +
                            '&public_electricity='          + id_public_electricity +
                            '&public_water='                + id_public_water +
                            '&public_electricity_elevator=' + id_public_electricity_elevator +
                            '&public_water_relay='          + id_public_water_relay +
                            '&property_balance_last='       +
                            '&property_balance_current=';

        //alert(dataString);

        $.ajax({
            type: "POST",
            url: "{{ app_root }}/api/add/bill/",
            data: dataString,
            success: function(data) {
                if(data=='fail')
                {

                }
                else
                {
                    //var content = $.parseJSON(data).content;
                    //alert(data);
                    $('#bill_list').prepend('<li class="ui-widget-content list_item">'+data+'</li>');
                    $('#list_count').text(parseInt($('#list_count').text())+1);

                    fit_ui_action_button();
                }
            }
        });
        return false;
    });

    fit_ui_datepicker('#id_bill_date');
</script>

apps/bills/templates/default/bills_config_edit.html
{% extends "default/bills_generic.html" %}
{% load i18n %}
{% block title %}{{ _("Config") }} -> {{ config.name|default:_("Add") }}{% endblock %}

{% block navigator %}
{% endblock %}

{% block content %}
    <form id="config_edit_form"enctype="multipart/form-data" action="." method="POST" accept-charset="utf-8">
        {% csrf_token %}
        <fieldset class="form_fields ui-widget-content">
            {{ form.as_ul }}
            <li>
                <input class="form_submit" type="submit" value="{{ _("Save") }}" title="{{ _("Save Data to System") }}"/>
            </li>
        </fieldset>
    </form>
{% endblock %}

apps/bills/templates/default/bills_location_edit.html
{% extends "default/bills_generic.html" %}
{% load i18n %}
{% block title %}{{ _("Bill Location") }} -> {{ location|default:_("Add") }}{% endblock %}

{% block navigator %}

{% endblock %}

{#{% block side_left %}#}
{#{% endblock %}#}

{% block content %}
    <form id="location_edit_form" enctype="multipart/form-data" action="." method="POST" accept-charset="utf-8">
        {% csrf_token %}
        <fieldset class="form_fields ui-widget-content">
            {{ form.as_ul }}
            <li>
                <input class="form_submit" type="submit" value="{{ _("Save") }}" title="{{ _("Save Data to System") }}"/>
            </li>
        </fieldset>
    </form>
    <script type="text/javascript">
        fit_ui_datepicker('#id_bought_date');
    </script>
{% endblock %}