apps/books/urls.py
# -*- coding: utf-8 -*-

__author__ = 'netcharm'

from django.conf.urls import patterns, url

from dajaxice.core import dajaxice_autodiscover
dajaxice_autodiscover()

import views
#from models import Book

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('apps.books.views',
    # Examples:
    # url(r'^$', 'apps.views.home', name='home'),
    # url(r'^apps/', include('apps.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),

    # Home List
    url(r'^$', views.index, name='index'),

    # Config Actions
    url(r'^config/$', views.configs.list, name='configs.list'),
    url(r'^config/add/$', views.configs.add, name='configs.add'),
    url(r'^config/(?P<config_id>(\w|\W)+)/edit/$', views.configs.edit, name='configs.edit'),
    url(r'^config/(?P<config_id>(\w|\W)+)/remove/$', views.configs.remove, name='configs.remove'),
    url(r'^config/get/$',views.configs.get, name='configs.get'),
    url(r'^config/set/$',views.configs.set, name='configs.set'),

    # Book Actions
    url(r'^search/$',views.books.search, name='books.search'),
    url(r'^list/$', views.books.list, name='books.list'),
    url(r'^add/$', views.books.add, name='books.add'),
    url(r'^add-multi/$', views.books.add_multi, name='books.add_multi'),
    url(r'^change-tag-multi/$', views.books.change_tag_multi, name='books.change_tag_multi'),
    url(r'^change-media-multi/$', views.books.change_media_multi, name='books.change_media_multi'),
    url(r'^change-state-multi/$', views.books.change_state_multi, name='books.change_state_multi'),
    url(r'^change-location-multi/$', views.books.change_location_multi, name='books.change_location_multi'),
    url(r'^change-category-multi/$', views.books.change_category_multi, name='books.change_category_multi'),
    url(r'^remove-multi/$', views.books.remove_multi, name='books.remove_multi'),
    url(r'^(?P<book_id>\d+)/edit/$', views.books.edit, name='books.edit'),
    url(r'^(?P<book_id>\d+)/remove/$', views.books.remove, name='books.remove'),
    url(r'^(?P<book_id>\d+)/note/$', views.books.note, name='books.note'),
    url(r'^(?P<book_id>\d+)/$', views.books.detail, name='books.detail'),
    url(r'^export/$', views.books._export, name='books.export'),
    url(r'^import/$', views.books._import, name='books.import'),

    # # Music Actions
    # url(r'^music/$', views.music.list, name='music.list'),
    # url(r'^music/add/$', views.music.add, name='music.add'),
    # url(r'^music/(?P<music_id>(\w|\W)+)/edit/$', views.music.edit, name='music.edit'),
    # url(r'^music/(?P<music_id>(\w|\W)+)/remove/$', views.music.remove, name='music.remove'),
    #
    # # Movie Actions
    # url(r'^movie/$', views.movie.list, name='movie.list'),
    # url(r'^movie/add/$', views.movie.add, name='movie.add'),
    # url(r'^movie/(?P<movie_id>(\w|\W)+)/edit/$', views.movie.edit, name='movie.edit'),
    # url(r'^movie/(?P<movie_id>(\w|\W)+)/remove/$', views.movie.remove, name='movie.remove'),

    # Category Actions
    url(r'^category/$', views.categories.list, name='categories.list'),
    url(r'^category/add/$', views.categories.add, name='categories.add'),
    url(r'^category/(?P<category_id>(\w|\W)+)/edit/$', views.categories.edit, name='categories.edit'),
    url(r'^category/(?P<category_id>(\w|\W)+)/remove/$', views.categories.remove, name='categories.remove'),

    # Location Actions
    url(r'^location/$', views.locations.list, name='locations.list'),
    url(r'^location/add/$', views.locations.add, name='locations.add'),
    url(r'^location/(?P<location_id>(\w|\W)+)/edit/$', views.locations.edit, name='locations.edit'),
    url(r'^location/(?P<location_id>(\w|\W)+)/remove/$', views.locations.remove, name='locations.remove'),

    # State Actions
    url(r'^state/$', views.states.list, name='states.list'),
    url(r'^state/add/$', views.states.add, name='states.add'),
    url(r'^state/(?P<state_id>(\w|\W)+)/edit/$', views.states.edit, name='states.edit'),
    url(r'^state/(?P<state_id>(\w|\W)+)/remove/$', views.states.remove, name='states.remove'),

    # Media Actions
    url(r'^media/$', views.medias.list, name='medias.list'),
    url(r'^media/add/$', views.medias.add, name='medias.add'),
    url(r'^media/(?P<media_id>(\w|\W)+)/edit/$', views.medias.edit, name='medias.edit'),
    url(r'^media/(?P<media_id>(\w|\W)+)/remove/$', views.medias.remove, name='medias.remove'),

    # Statistic Actions
    url(r'^report/$', views.reports.list, name='reports.list'),
    url(r'^report/add/$', views.reports.add, name='reports.add'),
    url(r'^report/data/$', views.reports.data, name='reports.data'),
    url(r'^report/(?P<report_id>(\w|\W)+)/Data.xml/$', views.reports.data_xml, name='reports.data_xml'),
    # url(r'^report/(?P<report_id>(\w|\W)+)/data/$', views.reports.data, name='reports.data'),
    url(r'^report/(?P<report_id>(\w|\W)+)/edit/$', views.reports.edit, name='reports.edit'),
    url(r'^report/(?P<report_id>(\w|\W)+)/remove/$', views.reports.remove, name='reports.remove'),
    url(r'^report/(?P<report_id>(\w|\W)+)/$', views.reports.detail, name='reports.detail'),

    # API url actions
    url(r'^api/test/$', views.api.test_json, name='views.api.test'),

)

apps/urls.py
# -*- coding: utf-8 -*-

__author__ = 'netcharm'

from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
#from django.contrib import admin
#admin.autodiscover()

from django.conf import settings

from dajaxice.core import dajaxice_autodiscover, dajaxice_config
dajaxice_autodiscover()

import apps
import views

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'apps.views.home', name='home'),
    # url(r'^apps/', include('apps.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    #url(r'^admin/', include(admin.site.urls)),
    
    # customize url
    url(r'^$', views.home, name='apps.home'),

    # Config Actions
    url(r'^config/$', views.configs.list, name='configs.list'),
    url(r'^config/add/$', views.configs.add, name='configs.add'),
    url(r'^config/(?P<config_id>(\w|\W)+)/edit/$', views.configs.edit, name='configs.edit'),
    url(r'^config/(?P<config_id>(\w|\W)+)/remove/$', views.configs.remove, name='configs.remove'),
    url(r'^config/get/$',views.configs.get, name='configs.get'),
    url(r'^config/set/$',views.configs.set, name='configs.set'),

    # API url actions
    url(r'^api/app/add/$', views.api.add_json, name='api.add.app'),
    url(r'^api/app/(?P<app_id>\d+)/get/$', views.api.get_json, name='api.app.get'),
    url(r'^api/app/(?P<app_id>\d+)/edit/$', views.api.edit_json, name='api.app.edit'),
    url(r'^api/app/(?P<app_id>\d+)/remove/$', views.api.remove_json, name='api.app.remove'),

    # app op function
    url(r'^(?P<app_id>\d+)/remove/$', views.apps.remove, name='apps.remove'),


    # My Apps
    url(r'^books/', include('apps.books.urls')),
    url(r'^bike/', include('apps.bike.urls')),
    url(r'^bills/', include('apps.bills.urls')),

    url(dajaxice_config.dajaxice_url, include('dajaxice.urls')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    
)

if settings.DEBUG:
    urlpatterns += patterns('django.contrib.staticfiles.views',
        url(r'^static/(?P<path>.*)$', 'serve'),
    )

apps/books/models.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

__author__ = 'netcharm'

#from django.contrib import admin
from django.db import models

from django.core.exceptions import ValidationError

from django.utils.translation import ugettext as _

from datetime import date

class Config(models.Model):
    name = models.CharField(_('Name'), max_length=32)
    value = models.CharField(_('Value'), max_length=256)

    def __unicode__(self):
        return self.name

    class Admin:
        pass


class BookEditValidator():

    @staticmethod
    def DigitValidator(value):
        if not value.isdigit():
            raise ValidationError(_(u'%s not a digit') % value)
        pass

    @staticmethod
    def isbn10(value):
        if not value.isdigit():
            raise ValidationError(_(u'%s not a digit') % value)
        if len(value) != 10:
            raise ValidationError(_(u'%s length less 10') % value)
            #if re.match(r’[+-]?\d+$’, ‘-1234′):
        pass

    @staticmethod
    def isbn13(value):
        if not value.isdigit():
            raise ValidationError(_(u'%s not a digit') % value)
        if len(value) != 13:
            raise ValidationError(_(u'%s length less 13') % value)
        pass
    name = models.CharField(_('Media'), max_length=32)

    def __unicode__(self):
        return self.name

    class Admin:
        pass


class Category(models.Model):
    name = models.CharField(_('Category'), max_length=32)

    def __unicode__(self):
        return self.name

    class Admin:
        pass


class Location(models.Model):
    name = models.CharField(_('Location'), max_length=32)

    def __unicode__(self):
        return self.name

    class Admin:
        pass


class State(models.Model):
    name = models.CharField(_('Location'), max_length=32)

    def __unicode__(self):
        return self.name

    class Admin:
        pass


class Media(models.Model):
    name = models.CharField(_('Media'), max_length=32)

    def __unicode__(self):
        return self.name

    class Admin:
        pass


class Statistic(models.Model):
    STYLE_CHOICES = (
        ( u'histogram', _('Histogram') ),
        ( u'line', _('Line') ),
        ( u'pie', _('Pie') ),
    )

    FIELD_CHOICES = (
        ( u'pubdate', _('Date Published') ),
        ( u'boughtdate', _('Date Bought') ),
        ( u'state', _('State') ),
        ( u'read_tags', _('Reading Tags') ),
        ( u'rating', _('Rating') ),
        ( u'category', _('Category') ),
        ( u'location', _('Location') ),
        ( u'media', _('Media') ),
        ( u'publisher', _('Publisher') ),
        ( u'binding', _('Binding') ),
        ( u'author', _('Author') ),
        ( u'translator', _('Translator') ),
    )

    CONDITION_CHOICES = (
        ( u'>' , _('>') ),
        ( u'>=', _('>=') ),
        ( u'=' , _('=') ),
        ( u'<=', _('<=') ),
        ( u'<' , _('<') ),
        ( u'*=' , _('*=') ),
    )

    name = models.CharField(_('Name'), max_length=32)
    style = models.CharField(_('Style'), max_length=32, choices=STYLE_CHOICES)
    # field = models.CharField(_('Field'), max_length=32, choices=FIELD_CHOICES)
    # condition = models.CharField(_('condition'), max_length=4, choices=CONDITION_CHOICES)
    # value = models.CharField(_('Value'), max_length=256)
    setting = models.CharField(_('Value'), max_length=256)
    template = models.CharField(_('Template'), max_length=256)

    def __unicode__(self):
        return self.name

    class Admin:
        pass


class Book(models.Model):
    today_str = format(u"(%s %s)" % (_("etc."), date.today().isoformat()))

    isbn10       = models.CharField(_('ISBN10'), default='', max_length=10, blank=True)#, validators=[BookEditValidator.isbn10])
    isbn13       = models.CharField(_('ISBN13'), max_length=13, validators=[BookEditValidator.isbn13])
    face_l       = models.URLField(_('Face_L'), default='', max_length=256, blank=True)
    face_m       = models.URLField(_('Face_M'), default='', max_length=256, blank=True)
    face_s       = models.URLField(_('Face_S'), default='', max_length=256, blank=True)
    title        = models.CharField(_('Title'), max_length=128)
    subtitle     = models.CharField(_('Subtitle'), default='', max_length=128, blank=True)
    pages        = models.SmallIntegerField(_('Pages'), default=0, blank=True, null=True)
    author       = models.CharField(_('Author'), default='', max_length=256, blank=True)
    translator   = models.CharField(_('Translator'), default='', max_length=256, blank=True)
    publisher    = models.CharField(_('Publisher'), default='', max_length=256, blank=True)
    price        = models.DecimalField(_('Price'), default=0, max_digits=5, decimal_places=2, blank=True,  null=True)
    boughtprice  = models.DecimalField(_('Price Bought'), default=0, max_digits=5, decimal_places=2, blank=True,  null=True)
    binding      = models.CharField(_('Binding'), default='', max_length=128, blank=True)
    pubdate      = models.DateField(_('Date Published'), blank=True, null=True, help_text=today_str)
    boughtdate   = models.DateField(_('Date Bought'), blank=True,  null=True, help_text=today_str)
    author_intro = models.TextField(_('Author Intro'), default='', blank=True)
    summary      = models.TextField(_('Summary'), default='', blank=True)
    tags         = models.TextField(_('Tags'), default='', blank=True)
    rating       = models.DecimalField(_('Rating'), default=0, max_digits=5, decimal_places=2, blank=True,  null=True)
    read_pages   = models.SmallIntegerField(_('Read Pages'), default=0, blank=True,  null=True, help_text=format(u"(%s)" % (_("Pages Be Read"))))
    read_start   = models.DateField(_('Reading Start'), blank=True,  null=True, help_text=today_str)
    read_end     = models.DateField(_('Reading Finished'), blank=True,  null=True, help_text=today_str)
    read_tags    = models.TextField(_('Reading Tags'), default='', blank=True)
    memo         = models.TextField(_('Memo'), default='', blank=True)
    state        = models.ForeignKey(State   , default=0, blank=True, null=True, verbose_name=_('State'))
    category     = models.ForeignKey(Category, default=0, blank=True, null=True, verbose_name=_('Category'))
    location     = models.ForeignKey(Location, default=0, blank=True, null=True, verbose_name=_('Location'))
    media        = models.ForeignKey(Media, default=0, blank=True, null=True, verbose_name=_('Media'))

    def __unicode__(self):
        return self.isbn13

    class Admin:
        pass


# class Music(models.Model):
#     today_str = format(u"(%s %s)" % (_("etc."), date.today().isoformat()))
#
#     isbn10       = models.CharField(_('ISBN10'), default='', max_length=10, blank=True, validators=[BookEditValidator.isbn10])
#     isbn13       = models.CharField(_('ISBN13'), max_length=13, validators=[BookEditValidator.isbn13])
#     face_l       = models.URLField(_('Face_L'), default='', max_length=256, blank=True)
#     face_m       = models.URLField(_('Face_M'), default='', max_length=256, blank=True)
#     face_s       = models.URLField(_('Face_S'), default='', max_length=256, blank=True)
#     title        = models.CharField(_('Title'), max_length=128)
#     subtitle     = models.CharField(_('Subtitle'), default='', max_length=128, blank=True)
#     author       = models.CharField(_('Author'), default='', max_length=256, blank=True)
#     translator   = models.CharField(_('Translator'), default='', max_length=256, blank=True)
#     publisher    = models.CharField(_('Publisher'), default='', max_length=256, blank=True)
#     price        = models.DecimalField(_('Price'), default=0, max_digits=5, decimal_places=2, blank=True,  null=True)
#     boughtprice  = models.DecimalField(_('Price Bought'), default=0, max_digits=5, decimal_places=2, blank=True,  null=True)
#     binding      = models.CharField(_('Binding'), default='', max_length=128, blank=True)
#     pubdate      = models.DateField(_('Date Published'), blank=True, null=True, help_text=today_str)
#     boughtdate   = models.DateField(_('Date Bought'), blank=True,  null=True, help_text=today_str)
#     author_intro = models.TextField(_('Author Intro'), default='', blank=True)
#     summary      = models.TextField(_('Summary'), default='', blank=True)
#     tags         = models.TextField(_('Tags'), default='', blank=True)
#     rating       = models.DecimalField(_('Rating'), default=0, max_digits=5, decimal_places=2, blank=True,  null=True)
#     read_pages   = models.SmallIntegerField(_('Read Pages'), default=0, blank=True,  null=True, help_text=format(u"(%s)" % (_("Pages Be Read"))))
#     read_start   = models.DateField(_('Reading Start'), blank=True,  null=True, help_text=today_str)
#     read_end     = models.DateField(_('Reading Finished'), blank=True,  null=True, help_text=today_str)
#     state        = models.ForeignKey(State   , default=0, blank=True, null=True, verbose_name=_('State'))
#     category     = models.ForeignKey(Category, default=0, blank=True, null=True, verbose_name=_('Category'))
#     location     = models.ForeignKey(Location, default=0, blank=True, null=True, verbose_name=_('Location'))
#     media        = models.ForeignKey(Media   , default=0, blank=True, null=True, verbose_name=_('Media'))
#
#     def __unicode__(self):
#         return self.title
#
#     class Admin:
#         pass
#
# class Movie(models.Model):
#     today_str = format(u"(%s %s)" % (_("etc."), date.today().isoformat()))
#
#     isbn10       = models.CharField(_('ISBN10'), default='', max_length=10, blank=True, validators=[BookEditValidator.isbn10])
#     isbn13       = models.CharField(_('ISBN13'), max_length=13, validators=[BookEditValidator.isbn13])
#     face_l       = models.URLField(_('Face_L'), default='', max_length=256, blank=True)
#     face_m       = models.URLField(_('Face_M'), default='', max_length=256, blank=True)
#     face_s       = models.URLField(_('Face_S'), default='', max_length=256, blank=True)

apps/books/templates/default/book_edit.html
{% extends "default/book_generic.html" %}

{% load i18n %}
{% load static %}

{% block title %}{{ _("Book") }} -> {{ book.title|default:_("Add") }}{% endblock %}

{% block dajax_script %}
    <script type="text/javascript" src="{% get_static_prefix %}js/dajax/jquery.dajax.core.js"></script>
    {% load dajaxice_templatetags %}
    {% dajaxice_js_import %}
    <script type="text/javascript">
        function adjust_button_douban()
        {
            //$("#id_isbn13").parent().append($("#button_douban_layer"));
            $("#id_isbn13").parent().append("&nbsp;");
            $("#id_isbn13").parent().append($("#button_douban_search"));
            $("#id_isbn13").parent().append("&nbsp;");
            $("#id_isbn13").parent().append($("#button_douban"));

            var datepicker_options = {
                dateFormat: "yy-mm-dd",
                monthNames: [ "{{ _("January") }}", "{{ _("February") }}", "{{ _("March") }}", "{{ _("April") }}", "{{ _("May") }}", "{{ _("June") }}", "{{ _("July") }}", "{{ _("August") }}", "{{ _("September") }}", "{{ _("October") }}", "{{ _("November") }}", "{{ _("December") }}" ],
                monthNamesShort: [ "{{ _("Jan") }}", "{{ _("Feb") }}", "{{ _("Mar") }}", "{{ _("Apr") }}", "{{ _("May") }}", "{{ _("Jun") }}", "{{ _("Jul") }}", "{{ _("Aug") }}", "{{ _("Sep") }}", "{{ _("Oct") }}", "{{ _("Nov") }}", "{{ _("Dec") }}" ],
                dayNames: [ "{{ _("Sunday") }}", "{{ _("Monday") }}", "{{ _("Tuesday") }}", "{{ _("Wednesday") }}", "{{ _("Thursday") }}", "{{ _("Friday") }}", "{{ _("Saturday") }}" ],
                dayNamesShort: [ "{{ _("Sun") }}", "{{ _("Mon") }}", "{{ _("Tue") }}", "{{ _("Wed") }}", "{{ _("Thu") }}", "{{ _("Fri") }}", "{{ _("Sat") }}" ],
                dayNamesMin: [ "{{ _("Su") }}", "{{ _("Mo") }}", "{{ _("Tu") }}", "{{ _("We") }}", "{{ _("Th") }}", "{{ _("Fr") }}", "{{ _("Sa") }}" ],
                weekHeader: "{{ _("Wk") }}",
{#                nextText: "{{ _("NEXT") }}",#}
{#                prevText: "{{ _("PREV") }}",#}
                nextText: "yy-mm",
                prevText: "yy-mm",
                //yearSuffix: "{{ _("CE") }}",
                firstDay: 1,
                changeMonth: true,
                changeYear: true,
                navigationAsDateFormat: true,
                //showWeek: true,
                showMonthAfterYear: true,
                constrainInput: true,
                yearRange: "1900:2100",
                maxDate: "+1m",
                //minDate: new Date(1950, 1, 1),
                hideIfNoPrevNext: true,
                gotoCurrent: true,
                autoSize: true
            };
            $('#id_read_start').datepicker( datepicker_options );
            $('#id_read_end').datepicker( datepicker_options );
            $('#id_pubdate').datepicker( datepicker_options );
            $('#id_boughtdate').datepicker( datepicker_options );
            
            var isbn13 = $('#id_isbn13').val();
            if(isbn13.length!=13)
            {
                $('#id_boughtdate').datepicker( 'setDate', 'today' );
            }

            $('#id_category').autocomplete();
        }

        function from_douban()
        {
            var isbn13 = $('#id_isbn13').val();
            if(isbn13.length==13)
            {
                if(isNaN(isbn13))
                {
                    return false;
                }
                else
                {
                    Dajaxice.apps.books.from_douban(Dajax.process, { 'book_id': isbn13 });
                    return true;
                }
            }
            return false;
        }
        
        function to_douban()
        {
            var isbn13 = $('#id_isbn13').val();
            if(isbn13.length==13)
            {
                if(isNaN(isbn13))
                {
                    return false;
                }
                else
                {
                    window.open("https://search.douban.com/book/subject_search?search_text=" + isbn13 +"&cat=1001", "Jump to douban.com Search Result Page");
                    return true;
                }
            }
            return false;
        }        
    </script>
{% endblock %}

{% block navigator %}

{% endblock %}

{#{% block side_left %}#}
{#{% endblock %}#}

{% block content %}
<div id="button_douban_layer">
    <a id="button_douban" class="action" onclick="from_douban();" title="{{ _("Get Information from douban.com") }}">{{ _("Douban") }}</a>
    <a id="button_douban_search" class="action" onclick="to_douban();" title="{{ _("Jump to douban.com Search Result Page") }}">{{ _("Douban Search") }}</a>
</div>

<form id="book_edit_form" enctype="multipart/form-data" action="." method="POST" accept-charset="utf-8">
    {% csrf_token %}
    <fieldset class="form_fields ui-widget-content">
        {{ form.as_ul }}
        <li>
            <input class="form_submit" type="submit" value="{{ _("Save") }}" title="{{ _("Save Data to System") }}"/>
        </li>
    </fieldset>
</form>
<script type="text/javascript">
    adjust_button_douban();
</script>
{% endblock %}

apps/books/templates/default/book_export_import.html
{% extends "default/book_generic.html" %}
{% load i18n %}
{% block title %}{{ _("Export") }}/{{ _("Import") }}{% endblock %}

{% block dajax_script %}
    <script type="text/javascript" src="{% get_static_prefix %}js/dajax/jquery.dajax.core.js"></script>
    {% load dajaxice_templatetags %}
    {% dajaxice_js_import %}
    <script type="text/javascript">
        var timer;
        var err_count = 0;

        function adjust_button_export()
        {
            //
            // Init progressbar when download books info from douban
            //
            $( "#ajax_progressbar" ).progressbar({
                value: 0,
                max: 100
            });
            return false;
        }

        function export_books()
        {
            err_count = 0;
            window.clearTimeout(timer);
            $( "#ajax_progressbar" ).progressbar("value", 0);

            $('#id_ajax_finished').val(0);
            $('#id_ajax_progress').val('');
            timer = window.setTimeout( get_progress, 250 );

            Dajaxice.apps.books.export_books(Dajax.process);

            return false;
        }

        function get_progress()
        {
            Dajaxice.apps.books.get_progress(Dajax.process);
            var ajax_finished = parseInt($('#id_ajax_finished').val());
            if((ajax_finished >= 100))
            {
                window.clearTimeout(timer);
                $( "#ajax_progressbar" ).progressbar("value", 100);
            }
            else
            {
                timer = window.setTimeout( get_progress, 250 );
                $( "#ajax_progressbar" ).progressbar("value", ajax_finished);
                //$( "#ajax_progressbar" ).progressbar(ajax_finished);
            }

            return false;
        }
    </script>
{% endblock %}

{% block navigator %}

{% endblock %}

{#{% block side_left %}#}
{#{% endblock %}#}

{% block content %}
    <div id="button_export_layer">
    </div>
    <form id="export_import_form" enctype="multipart/form-data" action="." method="POST" accept-charset="utf-8">
        {% csrf_token %}
        <fieldset class="form_fields ui-widget-content">
            <li>
                <input id="local_filename" type="file" />
            </li>
            <li>
                <div id="ajax_progressbar" class="progressbar"></div>
            </li>
            <li>
                <a id="button_douban" class="action" onclick="export_books();" title="{{ _("Export books to local") }}">{{ _("Export") }}</a>
            </li>
{#            <li>#}
{#                <input class="form_submit" type="submit" value="{{ _("Save") }}" title="{{ _("Save Data to System") }}"/>#}
{#            </li>#}
        </fieldset>
    </form>
    <script type="text/javascript">
        adjust_button_export();
    </script>
{% endblock %}

apps/books/templates/default/category_edit.html
{% extends "default/book_generic.html" %}
{% load i18n %}
{% block title %}{{ _("Book Category") }} -> {{ category|default:_("Add") }}{% endblock %}

{% block navigator %}

{% endblock %}

{#{% block side_left %}#}
{#{% endblock %}#}

{% block content %}
    <form id="category_edit_form" enctype="multipart/form-data" action="." method="POST" accept-charset="utf-8">
        {% csrf_token %}
        <fieldset class="form_fields ui-widget-content">
            {{ form.as_ul }}
            <li>
                <input class="form_submit" type="submit" value="{{ _("Save") }}" title="{{ _("Save Data to System") }}"/>
            </li>
        </fieldset>
    </form>
{% endblock %}

apps/books/templates/default/config_edit.html
{% extends "default/book_generic.html" %}
{% load i18n %}
{% block title %}{{ _("Config") }} -> {{ config.name|default:_("Add") }}{% endblock %}

{% block navigator %}
{% endblock %}

{% block content %}
    <form id="config_edit_form"enctype="multipart/form-data" action="." method="POST" accept-charset="utf-8">
        {% csrf_token %}
        <fieldset class="form_fields ui-widget-content">
            {{ form.as_ul }}
            <li>
                <input class="form_submit" type="submit" value="{{ _("Save") }}" title="{{ _("Save Data to System") }}"/>
            </li>
        </fieldset>
    </form>
{% endblock %}